### ISSUE TITLE
Critical error - Datakit crashing

### ISSUE THREAD

**Issue by bpahern** [MD2Korg/mCerebrum-DataKit#5]
Less than 5 minutes into testing the Study app, the app has crashed. There appears to be a problem with DataKit, or with the way DataKit and the Study app interact. There is an "Error: DataKit not available" message, and several attempts to correct this error resulted in a blank black screen. 

This problem first occurred after I viewed the Accelerometer plotter, but Tim thinks that was probably just a coincidence. Now the app is kind of stuck and further testing cannot be performed. It says DataKit is installed (green check mark) on the Install Application screen, but elsewhere in the Study app says that DataKit is not available.

**Comment by twhnat** [comment]
The apps tend to lock up with a black screen and manually deleting the database and associated folders did not resolve any issue

**Comment by twhnat** [comment]
This crash also tends to corrupt the database file, preventing retrieval of data.

**Comment by twhnat** [comment]
@bpahern Is this still a problem?

**Comment by bpahern** [comment]
@twhnat No, I haven't encountered it in recent updates.
